#!/bin/sh -l
#SBATCH -p serc
#SBATCH --job-name=energyDPS
#SBATCH --mem=50G
#SBATCH --time=100:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --output=energyDPS.out
#SBATCH --error=energyDPS.err

#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mofanz@stanford.edu

# Load necessary modules
module load python/3.9.0

# Activate your virtual environment (update to your env name)
source ~/endps/bin/activate



# Run your training script
python train_policy.py
